apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ls60iopem-nodejs
  janus-idp.io/tekton: ls60iopem-nodejs
  backstage.io/kubernetes-id: ls60iopem-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ls60iopem-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
